### ISSUE TITLE
Email Button has issues with safari on iPhone / Mac

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#103]
The activation link gets an additional localhost added to the url for some reason only in safari, other browser work fine.
`https://localhost/anmeldung.break-out.org/activation/:token`

**Comment by Ardobras** [comment]
After some reverse engineering it turs out the link is not `https://anmeldung...` but `https:///anmeldung...` so instead of `//` it contains `///`

**Comment by thepiwo** [comment]
thanks for resolving the issue
