### ISSUE TITLE
There is no endpoint to get a single event.

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#129]
Missing the endpoint `GET /event/{eventId}/`

**Comment by florianschmidt1994** [comment]
Do you need any more data at this endpoint (and if so which?) than the one provided for multiple events at `GET /event/`

**Comment by Ardobras** [comment]
This is a ticket for efficiency reasons. I tend to need only one event and
usually know which one so requesting a single event would make the backend
and frontend more efficient.

2016-05-16 13:01 GMT+02:00 Florian Schmidt <notifications@github.com>:
