### ISSUE TITLE
The unregisteredSponsor has to be dominant

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#134]
When I am a participant and also a sponsor and create a new offline sponsoring for my team, I will be the sponsor although I entered unregisteredSponsor data. If unregisteredSponsor data is entered the backend should prefer this kind of data.

**Comment by florianschmidt1994** [comment]
Do we want to handle this implicitly like you said it would it be reasonable to split this into multiple end points?

--
Gesendet von mobilem Gerät. Bin unterwegs.

Florian Schmidt
+49 15753003770

**Comment by Ardobras** [comment]
I think an implicit handling is enough for this season but we should probably split it into two endpoints for next year.

**Comment by florianschmidt1994** [comment]
I assume the same rule should apply to challenges?

**Comment by Ardobras** [comment]
correct
