### ISSUE TITLE
Handle teams who have not started

### ISSUE THREAD

**Issue by thepiwo** [BreakOutEvent/breakout-backend#135]
We will discus on monday @florianschmidt1994 @Ardobras

**Comment by florianschmidt1994** [comment]
Is this still an issue. Should we perhaps handle teams / filter data for teams who's hasStarted property is false during the time of the event?

**Comment by Ardobras** [comment]
Yes please. But we have the issue that no team has started yet and they
still need to post. Any solution for that?

**Comment by florianschmidt1994** [comment]
We will set `location.isDuringEvent` to `true` based on whether the `team.hasStarted` is set to true. As a consequence, only those locations are marked as isDuringEvent, where the team has started and the event is currently. Postings will not be affected by this and can be created by every team independent of their status
