### ISSUE TITLE
Create getPostingByTeam endpoint

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#138]

**Comment by thepiwo** [comment]
Is already done. You can call `GET /event/{eventId}/team/{teamId}/posting/` and receive all postingIds for given team.

breakout-frontend already has an endpoint to get multiple postings by ids

**Comment by thepiwo** [comment]
Added Enpoint in frontend:
https://github.com/BreakOutEvent/breakout-frontend/commit/ea7263ecd69222365fd75af5555ecb86bcb4789a#diff-39a721c2ab5d9cf2343cb3b04c04d4f9R635
