### ISSUE TITLE
add cache for slow requests. eg: donatesum for event

### ISSUE THREAD

**Issue by thepiwo** [BreakOutEvent/breakout-backend#142]

**Comment by thepiwo** [comment]
https://spring.io/guides/gs/caching/

**Comment by Ardobras** [comment]
The following routes should be cached:
`GET /event/`
`GET /event/{id}/team/`
`GET /event/{id}/team/{id}/`
`GET /event/{id}/team/{id}/posting/`
`GET /event/{id}/team/{id}/donatesum/`
`GET /event/{id}/team/{id}/distance/`
`GET /event/{id}/team/{id}/location/`

`GET /event/{id}/posting/`
`GET /event/{id}/donatesum/`
`GET /event/{id}/distance/`
`GET /event/{id}/location/`

`GET /user/`
`GET /user/{id}/sponsor/challenge/`
`GET /user/{id}/sponsor/sponsoring/`

`GET /posting/`

**Comment by thepiwo** [comment]
Added
`GET /event/` 5min
`GET /event/{id}/team/` 5min
`GET /event/{id}/team/{id}/` 1min
`GET /event/{id}/team/{id}/posting/` 1min
`GET /event/{id}/team/{id}/donatesum/` 1min
`GET /event/{id}/team/{id}/distance/` 1min
`GET /event/{id}/team/{id}/location/` 1min

`GET /event/{id}/posting/` 5min
`GET /event/{id}/donatesum/` 5min
`GET /event/{id}/distance/` 5min
`GET /event/{id}/location/` 5min

`GET /user/` 5min
`GET /user/{id}/sponsor/challenge/` none, as it would interfere with creating challenges
`GET /user/{id}/sponsor/sponsoring/` none, as it would interfere with creating sponsorings

`GET /posting/` 5min (only without limit/offset)

**Comment by thepiwo** [comment]
`/donatesum/` and `/distance/` calls are cached in two layers, so an uncached event call will be much faster, when part of the teams are still in cache. In extreme situations it could take up to 5+1 or 1+1 mis for these values to be at actual values
