### ISSUE TITLE
Location isDuringEvent use featureflag for event ended

### ISSUE THREAD

**Issue by thepiwo** [BreakOutEvent/breakout-backend#153]

**Comment by florianschmidt1994** [comment]
In this case I would remove the isDuringEvent function and prevent upload of locations in general (e.g. in the location service) based on whether the event has started or not. @thepiwo what do you think of this?

**Comment by florianschmidt1994** [comment]
@Ardobras do you rely on the isDuringEvent property for the location endpoint?

**Comment by thepiwo** [comment]
@florianschmidt1994 we have to filter locations, because apps havent implemented isDuringEvent
I would suggest a simple `locations.filter{ it.isDuringEvent() }`

**Comment by thepiwo** [comment]
these filters have to be at a low level, so distance and donate sum calculations are correct (all locations not during event excluded)

**Comment by florianschmidt1994** [comment]
But if we would ensure that the upload of locations is only allowed during the event at all, wouldn't we not need to filter those locations anyway?

**Comment by Ardobras** [comment]
@florianschmidt1994 the frontend currently filters locations based on `isDuringEvent` to decide if the location is displayed on the map.

**Comment by thepiwo** [comment]
@florianschmidt1994 we could do that, the advantage otherwise would be that we can change filtering behaviour afterwards and don't loose any location data

**Comment by florianschmidt1994** [comment]
Ok, i have a solution in progress using the method you described by saving isDuringEvent in the database
