### ISSUE TITLE
Transition from REJECTED to WITHDRAWN for status not allowed

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#159]
It should be allowed.

**Comment by thepiwo** [comment]
@florianschmidt1994 ?

**Comment by florianschmidt1994** [comment]
Should this be for both challenges and sponsoring? @Ardobras

**Comment by Ardobras** [comment]
Yes Both

2016-06-01 18:46 GMT+02:00 Florian Schmidt <notifications@github.com>:
