### ISSUE TITLE
Refactor UserCore / UserRole

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#184]
Proposed idea: Remove methods for user handling from interface, only implement in specific core methods
![c423b250-d925-48da-9b62-55fe6fe69fe1 1](https://cloud.githubusercontent.com/assets/6798306/21399792/6150c062-c7ad-11e6-9d48-058380f796d9.jpg)

**Comment by tgraupne** [comment]
One reason behind this proposed idea ist that since `UserRole`-Objects are implementing this interface, specific roles like `Sponsor`  can perform role manipulation which seems kind of strange.

**Comment by florianschmidt1994** [comment]
We made some changes here and are ok with the current state, so I'm going to close this issue.
