### ISSUE TITLE
Feature Flags to enable / disable features

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#33]
@leokaessner requested this.

An endpoint should be created, where a list of enabled / disabled features can be fetched from the server.

@leokaessner proposed `/user/{id}/init`, which should then also include information about available tshirt sizes and available events

**Comment by florianschmidt1994** [comment]
I would leave information about tshirtsizes and events to the respective API endpoints, I guess one more request to get that information should be bearable.

In terms of feature flags do we want to manage the overhead to organize those on a "per user" basis? Of course we could anyhow always return the same response for requests to `/user/{id}/features/`

**Comment by leokaessner** [comment]
For me it is ok, to separate Feature-Flagging from all the other information. But where do you like to give us the information about T-Shirt sizes, Events, Start Date and further possible presets? I don't think that we always can fit them to one of the existing endpoints, as it is a mix of setup and preset information. Isn't it?!

**Feature-Flags**
Definitely only provide one set for all! It is enough for now. However, I would use the /user/{id}/features/ endpoint as we could afterwards easily make it personal without touching the apps.

**Comment by florianschmidt1994** [comment]
In which format and which content should the data of the feature flags include? I guess this is highly dependant on how you integrate these features in the apps. Maybe just propose a format and we will serve a static file for now?

I think we should discuss the topic of initial data in a separate issue, see #34

**Comment by leokaessner** [comment]
I would really like to simply get an JSON with the following structure: 

`{
  "featureflag-Name-A" : true,
  "featureflag-Name-B" : false
}`

For now I would only like to have boolean values as it simply toggles on/off some of the features.

**Comment by thepiwo** [comment]
Maybe the HTTP-OPTIONS feature would be perfect to use for this issue

**Comment by florianschmidt1994** [comment]
This will be continued in BreakoutEvent/breakout-featureflags
