### ISSUE TITLE
Add fallback strategy if mailer not available

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#38]
If the breakout-mailer is not available, a suitable strategy must be chosen to provide some kind of fallback. Currently the idea is the user a queue, which would be a separate part of the backend architecture. This somehow depends on what @tpfeifle found out about using message queues such as rabbitMQ or redis

**Comment by thepiwo** [comment]
write failed sends to database, so they can be resend in the future

**Comment by thepiwo** [comment]
- files are not yet saved to DB
 - retry script should be implemented
