### ISSUE TITLE
Handle upload of media

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#4]
The upload of media (photos/videos) should be handled properly. 
In terms of storage we maybe should use some kind of CDN (AWS Bucket / Cloudflare / something else) in order to solve this.
Also the issue of linking data to the model needs to be solved. There is an interesting discussion here: http://stackoverflow.com/questions/3938569/how-do-i-upload-a-file-with-metadata-using-a-rest-web-service

**Comment by thepiwo** [comment]
Media files will be created as Model when creating a Post. The files will be uploaded via some "uploader-service" to the server running the "media-recode-service".
The recode-service will then upload the converted files to S3 and POST back to the Media Model, to update with URLs when the files are processed
