### ISSUE TITLE
Convert media to different formats

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#5]
In order to provide a good service for users with small bandwidth it may be useful to convert uploaded media to different sizes / resolutions or even file formats.
We need to decide whether we want to solve this using existing services or by implementing our own. After that the decided mechanism needs to be integrated in our system.

**Comment by thepiwo** [comment]
will be done with
https://github.com/thepiwo/media-recode-watcher
