### ISSUE TITLE
API for getting updated entries (e.g. postings)

### ISSUE THREAD

**Issue by tinobo** [BreakOutEvent/breakout-backend#60]
There should be an endpoint to get all IDs of entries that changed since the last update.
Every request to this endpoint should also return the request timestamp. This would allow the clients to store the timestamp of their last request for the next request.

**Comment by florianschmidt1994** [comment]
For now this can be solved with the the endpoints for specific ids in combination with the since endpoint. Will reopen / update if needed for the next version
