### ISSUE TITLE
Add timestamp when data is "created" at client (e.g. posts or locations)

### ISSUE THREAD

**Issue by florianschmidt1994** [BreakOutEvent/breakout-backend#72]

**Comment by thepiwo** [comment]
field in posting entity already exists, maybe we have to communicate on a common name (its "date" in posting currently)

**Comment by florianschmidt1994** [comment]
Not only would it be reasonable to define a common name, but we should also find a way to integrate this information into all entities which get created from requests of the apps. This data always might get created / measured / etc. on the device way before it gets sent to our server
