### ISSUE TITLE
Add basic logging

### ISSUE THREAD

**Issue by thepiwo** [BreakOutEvent/breakout-backend#86]

**Comment by florianschmidt1994** [comment]
Just as a note, Spring already supports pretty sophisticated logging methods using Apache Log4J. An instance of the logger can be obtained with `val logger = Logger.getLogger(CurrentClass::class.java)` allowing use to sort logs to classes. 
Furthermore with Log4j we should be able to attach different appenders, allowing us to seamlessly switch betwenn File / Logstash / whatever

**Comment by florianschmidt1994** [comment]
Nevertheless we need to actually use those logging functionalities 😂

**Comment by florianschmidt1994** [comment]
Removed from Milestone 1.0 as first deployment has already been done

**Comment by florianschmidt1994** [comment]
Logging is integrated and can be used.
