### ISSUE TITLE
Team Creation Request Returns 500

### ISSUE THREAD

**Issue by Ardobras** [BreakOutEvent/breakout-backend#87]
A request at the endpoint `POST /event/EVENTID/team/`with the following body `{"name":"test" }` returns 
```{ timestamp: 1461159279755,
  status: 500,
  error: 'Internal Server Error',
  exception: 'kotlin.KotlinNullPointerException',
  message: 'No message available',
  path: '/event/1/team/' }```

**Comment by florianschmidt1994** [comment]
I would need to know more about the details, but this might be related to #77, where a DomainException should be handled correctly and display some message because a business requirement was not met.

**Comment by florianschmidt1994** [comment]
Found the cause: The 500 error message is sent back to the client because the description in the body is missing. I will change the description of a team to being optional. Anyhow we should see why this is a NullPointerException resulting in 500 rather than an validation error returning BadRequest

**Comment by florianschmidt1994** [comment]
For now the team description will be set to "" if no description was provided via the API. This could be changed to make the description entirely optional, but for now I will set "" as default
